# Overrides values from https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-demo/values.yaml
default:
  image:
    repository: us-docker.pkg.dev/$PROJECT_ID/gcr.io/demo
    tag: "$DEMO_VERSION"
    pullPolicy: Always
  envOverrides:
    - name: OTEL_COLLECTOR_NAME
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP

opentelemetry-collector:
  mode: daemonset
  config:
    processors:
      resourcedetection:
        detectors: [gcp]

    exporters:
      otlp/nrdot:
        endpoint: '{{ include "otel-demo.name" . }}-nrotelcol:4317'
        tls:
          insecure: true
      otlphttp/newrelic:
        endpoint: $NEW_RELIC_OTLP_ENDPOINT
        headers:
          api-key: $NEW_RELIC_API_KEY_OTEL

    service:
      pipelines:
        traces:
          processors: [memory_limiter, resource, resourcedetection, batch]
          exporters: [otlp, debug, spanmetrics, otlp/newrelic]
        metrics:
          receivers: [otlp, spanmetrics]
          processors: [memory_limiter, resource, resourcedetection, batch]
          exporters: [otlphttp/prometheus, debug, otlp/newrelic]
        logs:
          processors: [memory_limiter, resource, resourcedetection, batch]
          exporters: [opensearch, debug, otlp/newrelic]
