# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: "Build and Publish"

on:
  release:
    types: [published]

jobs:
  build_and_push_images:
    uses: ./.github/workflows/build-images.yml
    if: github.repository == 'newrelic-forks/opentelemetry-demo'
    with:
      push: false
      push_new_relic: true
      version: ${{ github.event.release.tag_name }}
    secrets: inherit
